package fees2;



import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.*;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Anshika Computer
 */
public class login_page extends javax.swing.JFrame {

    /**
     * Creates new form login_page
     */
    public login_page() {
        initComponents();
    }

    void passwordValidation(String username,String password){
        try{
                 Class.forName("com.mysql.cj.jdbc.Driver");
           //to connect database
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=CONVERT_TO_NULL","root","123");
            String sql="select * from signup where Username=? and password=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,username);
            pst.setString(2, password);
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                 JOptionPane.showMessageDialog(this,"login succusfully");

                home home=new home(); 
                home.show();
                this.dispose();
                
            }
            else{
                JOptionPane.showMessageDialog(this,"enter valid password");
            }
    }
        catch(Exception e){
           e.printStackTrace();
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        inusername = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        exist1 = new javax.swing.JButton();
        errorshow = new javax.swing.JLabel();
        inpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Login page");

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(167, 167, 167))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 90));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password.setText("Password :");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 125, -1, -1));

        username1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        username1.setText("Username :");
        jPanel1.add(username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 71, -1, -1));

        inusername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inusernameActionPerformed(evt);
            }
        });
        jPanel1.add(inusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 68, 129, -1));

        login.setBackground(new java.awt.Color(0, 0, 102));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 169, -1, 28));

        signup.setBackground(new java.awt.Color(0, 0, 102));
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup.png"))); // NOI18N
        signup.setText("Sign_up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        jPanel1.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 169, -1, 27));

        exist1.setBackground(new java.awt.Color(0, 0, 102));
        exist1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exist1.setForeground(new java.awt.Color(255, 255, 255));
        exist1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exist1.setText("Exist");
        exist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exist1ActionPerformed(evt);
            }
        });
        jPanel1.add(exist1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 168, -1, 28));

        errorshow.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(errorshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 159, 207, -1));

        inpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(inpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 125, 129, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, 270));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inusernameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String uname=inusername.getText();
        String password=inpassword.getText();
        
        if(uname.trim().equals("")||password.trim().equals("")){
           errorshow.setText("enter username/password");
            
        }
        else{
             passwordValidation(uname,password);
        }
       
    }//GEN-LAST:event_loginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        sign_up sign_up=new sign_up();
        sign_up.show();
        this.dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void exist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exist1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exist1ActionPerformed

    private void inpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorshow;
    private javax.swing.JButton exist1;
    private javax.swing.JPasswordField inpassword;
    private javax.swing.JTextField inusername;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JLabel password;
    private javax.swing.JButton signup;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables
}
