package fees2;



import java.awt.Color;

import java.sql.PreparedStatement;
import java.sql.DriverManager;
import static java.lang.reflect.Array.get;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.*;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterJob;
import java.awt.print.PrinterException;
import java.awt. Graphics2D;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Anshika Computer
 */
public class printreciept extends javax.swing.JFrame {

    /**
     * Creates new form printreciept
     */
    public printreciept() {
        initComponents();
        printdata();
    }
   public void printdata(){
       try{
     Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=CONVERT_TO_NULL","root","123");
        PreparedStatement smpt=con.prepareStatement("select * from fees_details order by reciept_no desc limit 1") ;
        ResultSet rs=smpt.executeQuery();
        rs.next();
        reciept.setText(rs.getString("reciept_no"));
        tmop.setText(rs.getString("payment_mode"));
        String pmod=rs.getString("payment_mode");
        if(pmod.equalsIgnoreCase("cash")){
            ccdd.setText("cheque_no");
             tccdd.setText("--");
             tbank_name.setText("--");
              transaction.setText("--");
        }
        if(pmod.equalsIgnoreCase("cheque")){
            ccdd.setText("cheque_no");
             tccdd.setText(rs.getString("cheque_no"));
             tbank_name.setText(rs.getString("bank_name"));
              transaction.setText("--");
        }
         if(pmod.equalsIgnoreCase("dd")){
            ccdd.setText("dd_no");
             tccdd.setText(rs.getString("dd_no"));
             tbank_name.setText(rs.getString("bank_name"));
              transaction.setText("--");
        }
          if(pmod.equalsIgnoreCase("card")){
            ccdd.setText("cheque_no");
             tccdd.setText("--");
             tbank_name.setText(rs.getString("bank_name"));
             transaction.setText("--");
        }
          if(pmod.equalsIgnoreCase("upi")){
                ccdd.setText("cheque_no");
             tccdd.setText("--");
             tbank_name.setText(rs.getString("bank_name"));
             transaction.setText(rs.getString("transaction_id"));
          }
          treceived.setText(rs.getString("student_name"));
          tyear1.setText(rs.getString("year1"));
          tyear2.setText(rs.getString("year2"));
          sgst1.setText(rs.getString("sgst"));
          cgst1.setText(rs.getString("cgst"));
           fees1.setText(rs.getString("amount"));
          total.setText(rs.getString("total_amount"));
         date.setText(rs.getString("date"));
         roll.setText(rs.getString("roll_no"));
         gst.setText(rs.getString("gst_no"));
         remark.setText(rs.getString("remark"));
         courses.setText(rs.getString("courses"));
         ossgst.setText(rs.getString("isgst"));
         oc_gst1.setText(rs.getString("icgst"));
         
         
         
          
        
   }
      catch(Exception e){
          e.printStackTrace();
      } 
   }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Home2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchreport = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        editcourse = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        courselist = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        viewall = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        back = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        logout1 = new javax.swing.JPanel();
        print = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        bedit = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        reciept = new javax.swing.JLabel();
        tmop = new javax.swing.JLabel();
        tccdd = new javax.swing.JLabel();
        tbank_name = new javax.swing.JLabel();
        treceived = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tyear2 = new javax.swing.JLabel();
        roll = new javax.swing.JLabel();
        ccdd = new javax.swing.JLabel();
        mop = new javax.swing.JLabel();
        bank_name1 = new javax.swing.JLabel();
        received1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        tyear1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        remark = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        courses = new javax.swing.JLabel();
        course1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        fees1 = new javax.swing.JLabel();
        sgst1 = new javax.swing.JLabel();
        cgst1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        gst = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        transaction = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ossgst = new javax.swing.JLabel();
        oc_gst1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home2.setBackground(new java.awt.Color(0, 0, 102));
        Home2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        Home2.setVerifyInputWhenFocusTarget(false);
        Home2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Home2MouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jLabel3.setText("      Home ");

        javax.swing.GroupLayout Home2Layout = new javax.swing.GroupLayout(Home2);
        Home2.setLayout(Home2Layout);
        Home2Layout.setHorizontalGroup(
            Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        Home2Layout.setVerticalGroup(
            Home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel3.add(Home2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        searchreport.setBackground(new java.awt.Color(0, 0, 102));
        searchreport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        searchreport.setVerifyInputWhenFocusTarget(false);
        searchreport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchreportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchreportMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search2.png"))); // NOI18N
        jLabel4.setText("   Search report");

        javax.swing.GroupLayout searchreportLayout = new javax.swing.GroupLayout(searchreport);
        searchreport.setLayout(searchreportLayout);
        searchreportLayout.setHorizontalGroup(
            searchreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchreportLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        searchreportLayout.setVerticalGroup(
            searchreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE)
        );

        jPanel3.add(searchreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 142, 330, -1));

        editcourse.setBackground(new java.awt.Color(0, 0, 102));
        editcourse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        editcourse.setVerifyInputWhenFocusTarget(false);
        editcourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editcourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editcourseMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit2.png"))); // NOI18N
        jLabel2.setText("  Edit course");

        javax.swing.GroupLayout editcourseLayout = new javax.swing.GroupLayout(editcourse);
        editcourse.setLayout(editcourseLayout);
        editcourseLayout.setHorizontalGroup(
            editcourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editcourseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        editcourseLayout.setVerticalGroup(
            editcourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editcourseLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel3.add(editcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 214, 330, -1));

        courselist.setBackground(new java.awt.Color(0, 0, 102));
        courselist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        courselist.setVerifyInputWhenFocusTarget(false);
        courselist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                courselistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                courselistMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/list_1.png"))); // NOI18N
        jLabel5.setText(" Course list");

        javax.swing.GroupLayout courselistLayout = new javax.swing.GroupLayout(courselist);
        courselist.setLayout(courselistLayout);
        courselistLayout.setHorizontalGroup(
            courselistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courselistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        courselistLayout.setVerticalGroup(
            courselistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courselistLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel3.add(courselist, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 292, 330, -1));

        viewall.setBackground(new java.awt.Color(0, 0, 102));
        viewall.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        viewall.setVerifyInputWhenFocusTarget(false);
        viewall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewallMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewallMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view all record.png"))); // NOI18N
        jLabel6.setText("View all record");

        javax.swing.GroupLayout viewallLayout = new javax.swing.GroupLayout(viewall);
        viewall.setLayout(viewallLayout);
        viewallLayout.setHorizontalGroup(
            viewallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewallLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        viewallLayout.setVerticalGroup(
            viewallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.add(viewall, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 364, 330, -1));

        back.setBackground(new java.awt.Color(0, 0, 102));
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        back.setVerifyInputWhenFocusTarget(false);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back1.png"))); // NOI18N
        jLabel8.setText("        Back");

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 434, 330, -1));

        logout.setBackground(new java.awt.Color(0, 0, 102));
        logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        logout.setVerifyInputWhenFocusTarget(false);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jLabel11.setText("      Logout ");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 504, -1, -1));

        logout1.setBackground(new java.awt.Color(0, 0, 102));
        logout1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        logout1.setVerifyInputWhenFocusTarget(false);
        logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout1MouseExited(evt);
            }
        });

        print.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer-.png"))); // NOI18N
        print.setText("      Print ");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logout1Layout = new javax.swing.GroupLayout(logout1);
        logout1.setLayout(logout1Layout);
        logout1Layout.setHorizontalGroup(
            logout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logout1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        logout1Layout.setVerticalGroup(
            logout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout1Layout.createSequentialGroup()
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 330, -1));

        edit.setBackground(new java.awt.Color(0, 0, 102));
        edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        edit.setVerifyInputWhenFocusTarget(false);
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bedit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bedit.setForeground(new java.awt.Color(255, 255, 255));
        bedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit2.png"))); // NOI18N
        bedit.setText("edit");
        bedit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beditMouseClicked(evt);
            }
        });
        edit.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 2, 249, 48));

        jPanel3.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 330, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 1040));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(51, 0, 255));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 204));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1490, 10));

        reciept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reciept.setText("Reciept no:-");
        background.add(reciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 80, -1));

        tmop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tmop.setText("Mode of Payment:-");
        background.add(tmop, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 120, -1));

        tccdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tccdd.setText("cheque_dd:-");
        background.add(tccdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 80, -1));

        tbank_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbank_name.setText("Bank Name:-");
        background.add(tbank_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 80, -1));

        treceived.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        treceived.setText("Received From:-");
        background.add(treceived, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Following payment in the college of office the the year");
        background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 350, -1));

        tyear2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tyear2.setText("2012");
        background.add(tyear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 50, -1));

        roll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        roll.setText("Roll.No:-");
        background.add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 140, -1));

        ccdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ccdd.setText("cheque_dd:-");
        background.add(ccdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 80, -1));

        mop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mop.setText("Mode of Payment:-");
        background.add(mop, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, -1));

        bank_name1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bank_name1.setText("Bank Name:-");
        background.add(bank_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 80, -1));

        received1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        received1.setText("Received From:-");
        background.add(received1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 120, -1));

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date.setText("Date:-");
        background.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 130, -1));

        tyear1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tyear1.setText("2012");
        background.add(tyear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 40, -1));

        jLabel1.setText("--");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Heads");
        background.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 120, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("S.No:-");
        background.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 120, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Amount(Rs)");
        background.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 120, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Receiver Signature:-");
        background.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 150, -1));

        remark.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        background.add(remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 290, 20));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 160, 10));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1000, 10));
        background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1000, 10));
        background.add(courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 220, 20));

        course1.setText("1");
        background.add(course1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 80, 20));
        background.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 90, 30));
        background.add(fees1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 90, 30));
        background.add(sgst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 90, 30));
        background.add(cgst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 90, 30));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("Reciept no:-");
        background.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 80, -1));

        gst.setText("G.S.T.No:-");
        background.add(gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 150, -1));

        jLabel12.setText("G.S.T.No:-");
        background.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Date:-");
        background.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 60, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Remark:-");
        background.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 120, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 90, 100));

        transaction.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        background.add(transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 100, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Roll.No:-");
        background.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 60, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Transaction_id:-");
        background.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 100, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("enter the % of cgst");
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 150, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("enter the % of sgst");
        background.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 150, 20));
        background.add(ossgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 60, 20));
        background.add(oc_gst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 60, 20));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, -60, 1010, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Home2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home2MouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,0,255);
        Home2.setBackground(clr);
    }//GEN-LAST:event_Home2MouseEntered

    private void searchreportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchreportMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,0,255);
        searchreport.setBackground(clr);
    }//GEN-LAST:event_searchreportMouseEntered

    private void searchreportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchreportMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,0,102);
        searchreport.setBackground(clr);
    }//GEN-LAST:event_searchreportMouseExited

    private void editcourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,0,255);
        editcourse.setBackground(clr);
    }//GEN-LAST:event_editcourseMouseEntered

    private void editcourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcourseMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,0,102);
        editcourse.setBackground(clr);
    }//GEN-LAST:event_editcourseMouseExited

    private void courselistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courselistMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,0,255);
        courselist.setBackground(clr);
    }//GEN-LAST:event_courselistMouseEntered

    private void courselistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courselistMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,0,102);
        courselist.setBackground(clr);
    }//GEN-LAST:event_courselistMouseExited

    private void viewallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewallMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,0,255);
        viewall.setBackground(clr);
    }//GEN-LAST:event_viewallMouseEntered

    private void viewallMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewallMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,0,102);
        viewall.setBackground(clr);
    }//GEN-LAST:event_viewallMouseExited

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,0,255);
        back.setBackground(clr);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        Color clr=new Color(0,0,102);
        back.setBackground(clr);
        // TODO add your handling code here:
    }//GEN-LAST:event_backMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(0,0,255);
        logout.setBackground(clr);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        Color clr=new Color(0,0,102);
        logout.setBackground(clr);
    }//GEN-LAST:event_logoutMouseExited

    private void Home2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home2MouseClicked
        // TODO add your handling code here:
         home home=new home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Home2MouseClicked

    private void logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1MouseEntered

    private void logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logout1MouseExited

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_editMouseExited

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:
          PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
      
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                

                 Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                background.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }

    }//GEN-LAST:event_printMouseClicked

    private void beditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseClicked
        // TODO add your handling code here:
        edit edit=new edit();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_beditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(printreciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(printreciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(printreciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(printreciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new printreciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home2;
    private javax.swing.JPanel back;
    private javax.swing.JPanel background;
    private javax.swing.JLabel bank_name1;
    private javax.swing.JLabel bedit;
    private javax.swing.JLabel ccdd;
    private javax.swing.JLabel cgst1;
    private javax.swing.JLabel course1;
    private javax.swing.JPanel courselist;
    private javax.swing.JLabel courses;
    private javax.swing.JLabel date;
    private javax.swing.JPanel edit;
    private javax.swing.JPanel editcourse;
    private javax.swing.JLabel fees1;
    private javax.swing.JLabel gst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel logout1;
    private javax.swing.JLabel mop;
    private javax.swing.JLabel oc_gst1;
    private javax.swing.JLabel ossgst;
    private javax.swing.JLabel print;
    private javax.swing.JLabel received1;
    private javax.swing.JLabel reciept;
    private javax.swing.JLabel remark;
    private javax.swing.JLabel roll;
    private javax.swing.JPanel searchreport;
    private javax.swing.JLabel sgst1;
    private javax.swing.JLabel tbank_name;
    private javax.swing.JLabel tccdd;
    private javax.swing.JLabel tmop;
    private javax.swing.JLabel total;
    private javax.swing.JLabel transaction;
    private javax.swing.JLabel treceived;
    private javax.swing.JLabel tyear1;
    private javax.swing.JLabel tyear2;
    private javax.swing.JPanel viewall;
    // End of variables declaration//GEN-END:variables
}
